---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  Private instances with a bastion and nat gateway
  
Parameters:
  
  # --------------------- Common parameters --------------------- #

  AppName:
    Description: Application name
    Type: String

  # ----------------------- Vpc paramters ----------------------- #

  VpcCidr:
    Description: VPC Cidr that allows the creation of 4 subnets with /27 mask 
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 172.31.0.0/16
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  # --------------------- Bation paramters --------------------- #

  BastionKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  SshLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  BastionInstanceType:
    Description: Bastion instance type
    Type: String
    Default: t2.micro 
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
      c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.
  BastionRootVolumeSize:
    Description: The size in GB for the root EBS volume.
    Type: Number
    Default: '8'
  S3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-scripts
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  S3BucketRegion:
    Default: 'us-east-1'
    Description: The AWS Region where the Quick Start S3 bucket (S3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  S3KeyPrefix:
    AllowedPattern: '^([0-9a-zA-Z-.])*$'
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), dots (.) and forward slash (/). The prefix should
      end with a forward slash (/).
    Default: 'linux-bastion'
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), dots
      (.) and forward slash (/) and it should end with a forward slash (/).
    Type: String
  EnvironmentVariables:
    Description: A comma-separated list of environment variables for use in
      bootstrapping. Variables must be in the format KEY=VALUE. VALUE cannot
      contain commas.
    Type: String
    Default: ''
  EnableTCPForwarding:
    Type: String
    Description: To enable TCP forwarding, choose true.
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  EnableX11Forwarding:
    Type: String
    Description: To enable X11 forwarding, choose true.
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  
  # --------------------- EKS node group paramters --------------------- #

  WorkersKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EKS workers.
  EksWorkerAmiReleaseVersion:
    Description: Eks node AMI release version
    Type: String
    Default: 1.15.10-20200228
  EksWorkerInstanceType:
    Description: Eks worker instance type
    Type: String
    Default: t2.micro 
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
      c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.
  DesiredWorkersCapacity:
    Description: Desired worker nodes capacity
    Type: Number
    Default: 2
  MinWorkersCapacity:
    Description: Minimum worker nodes capacity
    Type: Number
    Default: 2
  MaxWorkersCapacity:
    Description: Maximum worker nodes capacity
    Type: Number
    Default: 3

Resources:
  
  # -------------------- VPC stack --------------------- #

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParentStack: !Ref AWS::StackName
        AppName: !Ref AppName
        VpcCidr: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-VPC-Stack
      TemplateURL: vpc.yml #required
      TimeoutInMinutes: 5

  # ------------------ Bastion stack ------------------- #

  BastionStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      Parameters:
        ParentStack: !Ref AWS::StackName
        AppName: !Ref AppName
        KeyName: !Ref BastionKeyName
        SshLocation: !Ref SshLocation
        BastionInstanceType: !Ref BastionInstanceType
        BastionRootVolumeSize: !Ref BastionRootVolumeSize
        S3BucketName: !Ref S3BucketName
        S3BucketRegion: !Ref S3BucketRegion
        S3KeyPrefix: !Ref S3KeyPrefix
        EnvironmentVariables: !Ref EnvironmentVariables
        EnableTCPForwarding: !Ref EnableTCPForwarding
        EnableX11Forwarding: !Ref EnableX11Forwarding
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-Bastion-Host-Stack
      TemplateURL: bastion-host.yml #required
      TimeoutInMinutes: 45

  # ----------------- EKS Cluster stack ------------------ #

  EksStackCluster:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      Parameters:
        ParentStack: !Ref AWS::StackName
        AppName: !Ref AppName
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-EKS-Cluster-Stack
      TemplateURL: eks-cluster.yml #required
      TimeoutInMinutes: 5


  # ----------------- EKS workers stack ------------------ #

  EksWorkersCluster:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - EksStackCluster
      - BastionStack
    Properties:
      Parameters:
        ParentStack: !Ref AWS::StackName
        AppName: !Ref AppName
        KeyName: !Ref WorkersKeyName
        EksWorkerAmiReleaseVersion: !Ref EksWorkerAmiReleaseVersion
        EksWorkerInstanceType: !Ref EksWorkerInstanceType
        DesiredWorkersCapacity: !Ref DesiredWorkersCapacity
        MaxWorkersCapacity: !Ref MaxWorkersCapacity
        MinWorkersCapacity: !Ref MinWorkersCapacity
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-EKS-Cluster-Stack
      TemplateURL: eks-workers.yml #required
      TimeoutInMinutes: 5